from pathlib import Path

CUT='11 Sep 2026 · 23:37 MYT'

article=Path('news/2026/09/11/empat-atau-lima-didakwa-rekod-tidak-seragam/index.html')
article.parent.mkdir(parents=True,exist_ok=True)
article.write_text('''<!doctype html>
<html lang="ms"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Empat atau lima didakwa? Rekod RCI Tabung Haji tidak seragam | RAVEN-Trace</title>
<meta name="description" content="11 September 2026: rekod mahkamah yang disemak menunjukkan empat individu telah berdepan pertuduhan yang dibacakan, sementara SPRM menyebut lima. Raven mengaudit perbezaan itu.">
<link rel="canonical" href="https://raven-trace.github.io/raventrace-my/news/2026/09/11/empat-atau-lima-didakwa-rekod-tidak-seragam/">
<meta property="og:type" content="article"><meta property="og:site_name" content="RAVEN-Trace Malaysia"><meta property="og:title" content="Empat atau lima didakwa? Rekod tidak seragam"><meta property="og:description" content="Rekod mahkamah yang disemak menunjukkan empat; SPRM menyebut lima. Perbezaan itu perlu dijelaskan, bukan disenyapkan."><meta property="og:url" content="https://raven-trace.github.io/raventrace-my/news/2026/09/11/empat-atau-lima-didakwa-rekod-tidak-seragam/"><meta property="og:image" content="https://raven-trace.github.io/raventrace-my/assets/og/rci-tabung-haji-share-v6.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="https://raven-trace.github.io/raventrace-my/assets/og/rci-tabung-haji-share-v6.jpg">
<link rel="stylesheet" href="/raventrace-my/assets/css/raven.css?v=3.0.0"><link rel="stylesheet" href="/raventrace-my/assets/css/raven-publication.css?v=2.0.0"><script async src="https://lytcdn.com/lyt.js?site=7d23381ee4e5"></script></head><body><a class="skip-link" href="#main">Terus ke kandungan</a>
<header class="site-header"><div class="masthead"><a class="brand" href="/raventrace-my/"><span><span class="brand-name">RAVEN<em>-Trace</em></span><span class="brand-sub">Bebas · Berasaskan bukti · Malaysia</span></span></a><p class="masthead-note">Bukti dahulu.<br>Kesimpulan kemudian.</p></div><div class="nav-row"><div class="nav-wrap"><nav class="site-nav"><a href="/raventrace-my/">Utama</a><a aria-current="page" href="/raventrace-my/news/">Newsroom</a><a href="/raventrace-my/investigations/">Siasatan</a><a href="/raventrace-my/methodology/">Metodologi</a></nav></div></div></header>
<main id="main"><section class="story-hero"><div class="container"><p class="story-kicker">RCI Tabung Haji · Forensic update</p><div class="meta-row"><span class="status disputed">DISPUTED RECORD</span><span class="source-grade">Gred B · rekod awam</span></div><h1>Empat atau lima telah didakwa? Rekod awam yang disemak tidak seragam.</h1><p class="lede">Chronology mahkamah menunjukkan empat individu telah berdepan pertuduhan yang dibacakan. SPRM pula menyebut lima, termasuk bekas COO TH yang prosidingnya dilaporkan ditangguhkan ke 24 September.</p><p class="date-chip">11 Sep 2026 · disemak 23:37 MYT</p></div></section>
<section class="section paper"><div class="container story-body">
<h2>Apa yang rekod tunjuk?</h2><p>Berdasarkan chronology mahkamah dan laporan yang boleh diaudit, empat individu telah berdepan pertuduhan yang dibacakan setakat semakan ini: Nasahruddin Ahmad, Tengku Kamarolhisham Tengku Kamaruddin, Abdul Azeez Abdul Rahim dan Azmi Ahmad.</p><p>Dalam kenyataan berasingan, Ketua Pesuruhjaya SPRM dilaporkan menyebut lima individu telah didakwa. Kiraan itu memasukkan bekas COO TH Datuk Adi Azuan Abdul Ghani, sedangkan prosiding beliau sebelum ini dilaporkan ditangguhkan ke 24 September kerana faktor kesihatan.</p>
<div class="case-warning light"><strong>Verdict Raven</strong><span>Perbezaan 4 lawan 5 ialah <b>DISPUTED RECORD</b>, bukan alasan untuk memilih angka yang paling dramatik. Setakat rekod mahkamah yang kami semak, empat telah berdepan pertuduhan yang dibacakan. Pertuduhan bukan sabitan.</span></div>
<h2>Apa berubah hari ini?</h2><p>SPRM turut mengesahkan seorang bekas menteri akan didakwa pada Isnin, 14 September, dengan tiga pertuduhan yang dicadangkan di bawah Seksyen 403 Kanun Keseksaan berkaitan aset di Arab Saudi. Beberapa media mengenal pasti individu itu sebagai Jamil Khir Baharom. Raven mengekalkan status sebagai <b>prosecution notice</b> sehingga pertuduhan benar-benar dibacakan di mahkamah.</p>
<h2>Apa masih belum diketahui?</h2><p>Status selepas tamat tempoh reman 11 September bagi dua individu dalam trek AMLA belum dapat dikunci daripada sumber awam yang kami semak. Ketiadaan laporan tidak boleh ditafsir sebagai pelepasan, sambungan reman atau penutupan kes.</p>
<h2>Kenapa ini penting?</h2><p>RCI, siasatan, tangkapan, reman, keputusan untuk mendakwa, pertuduhan dibacakan, perbicaraan dan sabitan ialah tahap proses yang berbeza. Menggabungkannya menghasilkan angka yang nampak mudah tetapi boleh mengelirukan.</p>
<p><a href="https://www.bernama.com/bm/wilayah/news.php?id=2605567" rel="noopener noreferrer">Bernama · kenyataan SPRM →</a></p><p><a href="https://www.bernama.com/bm/am/news.php?id=2605694" rel="noopener noreferrer">Bernama · chronology mahkamah →</a></p><p><a href="/raventrace-my/investigations/rci-tabung-haji/updates/">Kembali ke tracker RCI →</a></p></div></section></main>
<footer class="site-footer"><div class="container footer-grid"><div><div class="footer-brand">RAVEN<em>-Trace</em>™</div><p class="motto">A lie wins by speed. Truth wins by audit.</p></div><p class="legal">RAVEN-Trace™ by SharulR X(ai) Projects. Semua individu dianggap tidak bersalah melainkan disabitkan oleh mahkamah.</p></div></footer></body></html>''')

# Newsroom: refresh cutoff + prepend forensic item.
p=Path('news/index.html'); s=p.read_text()
s=s.replace('Newsroom · disemak hingga 9 Sep 2026 · 17:26 MYT',f'Newsroom · disemak hingga {CUT}')
s=s.replace('Maklumat disemak hingga · 9 Sep 2026 · 17:26 MYT',f'Maklumat disemak hingga · {CUT}')
marker='<div class="timeline">'
item='''<article id="news-2026-09-11-count-discrepancy" class="timeline-item" data-topic="enforcement"><time datetime="2026-09-11">11 SEP 2026</time><div><div class="meta-row"><span class="status disputed">DISPUTED RECORD</span><span class="source-grade">Gred B</span></div><h3>Empat atau lima telah didakwa? Rekod awam tidak seragam.</h3><p>Chronology mahkamah yang disemak menunjukkan empat individu telah berdepan pertuduhan yang dibacakan. SPRM menyebut lima, termasuk bekas COO TH yang prosidingnya dilaporkan ditangguhkan ke 24 September.</p><a href="/raventrace-my/news/2026/09/11/empat-atau-lima-didakwa-rekod-tidak-seragam/">Baca siasatan Raven →</a></div></article>'''
if 'news-2026-09-11-count-discrepancy' not in s: s=s.replace(marker,marker+'\n      '+item,1)
p.write_text(s)

# Updates tracker: refresh metadata/cutoff, prepend 11 Sep card, replace stale NEXT queue.
p=Path('investigations/rci-tabung-haji/updates/index.html'); s=p.read_text()
s=s.replace('Disemak hingga 10 September 2026.','Disemak hingga 11 September 2026.')
s=s.replace('disemak hingga 10 September 2026.','disemak hingga 11 September 2026.')
s=s.replace('Maklumat disemak hingga · 10 Sep 2026 · 17:26 MYT',f'Maklumat disemak hingga · {CUT}')
stack='<div class="trace-stack">'
card='''<article class="trace-card"><div class="trace-head"><span>JEJAK / 11-01</span><time datetime="2026-09-11">11 Sep 2026 · rekod mahkamah + SPRM</time></div><div class="meta-row"><span class="status disputed">DISPUTED RECORD</span><span class="source-grade">Gred B</span></div><h3>Empat atau lima telah didakwa? Rekod awam yang disemak tidak seragam.</h3><dl><div><dt>Apa rekod tunjuk?</dt><dd>Chronology mahkamah menunjukkan empat individu telah berdepan pertuduhan yang dibacakan. SPRM menyebut lima dan memasukkan bekas COO TH yang prosidingnya dilaporkan ditangguhkan ke 24 September.</dd></div><div><dt>Verdict Raven</dt><dd>Setakat rekod mahkamah yang disemak, gunakan angka empat dan tandakan kiraan SPRM sebagai perbezaan yang belum dijelaskan. Pertuduhan bukan sabitan.</dd></div><div><dt>Apa berubah?</dt><dd>SPRM mengesahkan seorang bekas menteri akan didakwa 14 September dengan tiga pertuduhan dicadangkan di bawah Seksyen 403 Kanun Keseksaan. Ini ialah prosecution notice; pertuduhan belum dibacakan.</dd></div></dl><p class="inline-sources"><a href="/raventrace-my/news/2026/09/11/empat-atau-lima-didakwa-rekod-tidak-seragam/">Siasatan Raven</a> · <a href="https://www.bernama.com/bm/wilayah/news.php?id=2605567" rel="noopener noreferrer">Bernama</a></p></article>'''
if 'JEJAK / 11-01' not in s: s=s.replace(stack,stack+card,1)
old='<p class="section-lead"><strong>11 Sep:</strong> pantau keputusan reman dua individu dalam trek AMLA serta sebarang perkembangan PDRM berkaitan hibah. <strong>Jamil Khir:</strong> laporan awal menyebut kemungkinan tindakan mahkamah pada 17 September, tetapi tarikh, seksyen dan pertuduhan sebenar masih belum disahkan. <strong>24 Sep:</strong> prosiding seterusnya bagi Adi Azuan selepas pertuduhan terdahulu ditunda.</p>'
new='<p class="section-lead"><strong>14 Sep:</strong> pantau prosiding bekas menteri yang SPRM sahkan akan menghadapi tiga pertuduhan dicadangkan di bawah Seksyen 403 Kanun Keseksaan; media mengenal pasti beliau sebagai Jamil Khir Baharom, tetapi Raven menunggu pertuduhan dibacakan. <strong>AMLA:</strong> status selepas tamat tempoh reman 11 September masih belum disahkan melalui sumber awam yang kami semak. <strong>24 Sep:</strong> prosiding seterusnya bagi Adi Azuan; checkpoint ini juga penting untuk menyelesaikan discrepancy kiraan empat lawan lima.</p>'
s=s.replace(old,new)
p.write_text(s)

print('11 Sep investigation update applied')
