from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def patch(path, old, new, label):
    p = ROOT / path
    text = p.read_text(encoding='utf-8')
    if new in text:
        print('already', label)
        return
    if old not in text:
        raise RuntimeError(f'missing pattern for {label} in {path}')
    p.write_text(text.replace(old, new, 1), encoding='utf-8')
    print('patched', label)


def patch_all(path, pairs):
    p = ROOT / path
    text = p.read_text(encoding='utf-8')
    changed = False
    for old, new, label in pairs:
        if new in text:
            print('already', label)
            continue
        if old not in text:
            raise RuntimeError(f'missing pattern for {label} in {path}')
        text = text.replace(old, new, 1)
        changed = True
        print('patched', label)
    if changed:
        p.write_text(text, encoding='utf-8')


# Homepage: freshness, v17, current lead and financial follow-up.
patch_all('index.html', [
    ('Ahad · 6 September 2026 · Malaysia', 'Isnin · 7 September 2026 · Malaysia', 'home utility date'),
    ('Maklumat disemak hingga · 6 Sep 2026 · awal pagi MYT', 'Maklumat disemak hingga · 7 Sep 2026 · awal pagi MYT', 'home cutoff'),
    ('CASEFILE / RCI-TH-2026 · v16', 'CASEFILE / RCI-TH-2026 · v17', 'home case version'),
    ('Kemas kini yang disahkan · 5–6 September', 'Kemas kini yang disahkan · 6–7 September', 'home latest range'),
    ('''<article id="home-2026-09-06-jamil-reman-checkpoint" class="update-card lead-update"><div class="update-index">01</div><div class="meta-row"><span class="status unknown">Checkpoint hari ini</span><time datetime="2026-09-06">6 Sep 2026</time></div><h3>Tempoh reman Jamil Khir berakhir hari ini; keputusan seterusnya belum diumumkan.</h3><p>Beliau direman lima hari bagi membantu siasatan berkaitan pajakan hotel Tabung Haji di Arab Saudi. Setakat semakan awal pagi, belum ada rekod awam yang mengesahkan sama ada beliau dibebaskan, reman dilanjutkan atau akan didakwa.</p><a href="/raventrace-my/investigations/rci-tabung-haji/#people">Lihat status individu →</a><br><a href="https://www.malaysiakini.com/news/783373" rel="noopener noreferrer">Sumber: Malaysiakini / prosiding reman →</a></article>''', '''<article id="home-2026-09-06-jamil-reman-checkpoint" class="update-card lead-update"><div class="update-index">01</div><div class="meta-row"><span class="status process">Reman disambung · belum didakwa</span><time datetime="2026-09-06">6 Sep 2026</time></div><h3>Mahkamah sambung reman bekas menteri dua hari, hingga 8 September.</h3><p>Mahkamah Majistret Putrajaya membenarkan permohonan SPRM menyambung reman dua hari lagi bagi siasatan berkaitan pajakan hotel TH di Arab Saudi. SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009. Reman bukan pertuduhan atau sabitan.</p><a href="/raventrace-my/news/2026/09/06/jamil-khir-reman-checkpoint/">Baca artikel →</a><br><a href="https://web26.bernama.com/bm/jenayah_mahkamah/news.php?id=2603643" rel="noopener noreferrer">Sumber: Bernama / prosiding reman →</a></article>''', 'home Jamil lead'),
    ('''<article id="home-2026-09-04-madinah-rashid" class="update-card"><div class="update-index">04</div><div class="meta-row"><span class="status disputed">Rekod bercanggah</span><time datetime="2026-09-04">4 Sep 2026</time></div><h3>Madinah Mohamad dan Rashid Hussain memberi versi berbeza tentang prosiding RCI.</h3><p>Sapina dan 75 jawapan bertulis disokong kedua-dua versi. Yang masih dipertikaikan ialah apa yang berlaku ketika Madinah hadir dan sama ada beliau diberi peluang memberi keterangan lisan.</p><a href="/raventrace-my/investigations/rci-tabung-haji/#disputed-record">Lihat analisis Raven →</a><br><a href="https://berita.rtm.gov.my/nasional/senarai-berita-nasional/senarai-artikel/dakwaan-tan-sri-madinah-tidak-dipanggil-rci-tabung-haji-tidak-benar-tan-sri-rashid/" rel="noopener noreferrer">Sumber: versi Rashid</a> · <a href="https://www.freemalaysiatoday.com/category/bahasa/tempatan/2026/09/04/madinah-nafi-minta-beri-keterangan-kepada-rci-th-bersama-pegawai-lain" rel="noopener noreferrer">Sumber: versi Madinah</a></article>''', '''<article id="home-2026-09-03-ujsb-sukuk-refinancing" class="update-card"><div class="update-index">04</div><div class="meta-row"><span class="status context">Kewangan · pembiayaan semula</span><time datetime="2026-09-03">3 Sep 2026</time></div><h3>RM11.5 bilion sukuk UJSB diterangkan sebagai pembiayaan semula, bukan bailout baharu.</h3><p>Penjelasan yang dilaporkan Bernama menyatakan sukuk baharu menggantikan sukuk UJSB terdahulu dan memberi aliran tunai tahunan kepada TH. Angka ini tidak patut dicampur sebagai “kerugian baharu” dalam kiraan RM13 bilion.</p><a href="/raventrace-my/investigations/rci-tabung-haji/#money">Semak konteks UJSB →</a><br><a href="https://bernama.com/radio/news.php?id=2602611" rel="noopener noreferrer">Sumber: Bernama →</a></article>''', 'home sukuk card'),
    ('<a href="/raventrace-my/investigations/rci-tabung-haji/">Siasatan</a>', '<a href="/raventrace-my/investigations/">Siasatan</a>', 'home investigation nav/footer first occurrence'),
    ('47+ rujukan dengan gred bukti', '50+ rujukan dengan gred bukti', 'home source count'),
    ('/assets/js/raven.js?v=3.2.0', '/assets/js/raven.js?v=3.4.0', 'home JS cache bust'),
])

# Newsroom: current top story, financial follow-up and cutoff.
patch_all('news/index.html', [
    ('Maklumat disemak hingga · 6 Sep 2026 · awal pagi MYT', 'Maklumat disemak hingga · 7 Sep 2026 · awal pagi MYT', 'news cutoff'),
    ('''<article id="news-2026-09-06-jamil-reman-checkpoint" class="timeline-item" data-topic="enforcement"><time datetime="2026-09-06">06 SEP 2026</time><div><div class="meta-row"><span class="status unknown">Outcome belum diumumkan</span><span class="source-grade">Gred B</span></div><h3>Tempoh reman Jamil Khir berakhir hari ini</h3><p>Reman lima hari yang bermula 2 September dijadual berakhir hari ini. Setakat semakan awal pagi, belum ada rekod awam yang mengesahkan sama ada beliau dibebaskan, reman dilanjutkan atau akan didakwa. Status kekal UNKNOWN sehingga ada rekod baharu.</p><a href="/raventrace-my/investigations/rci-tabung-haji/#people">Status individu →</a><br><a href="https://www.malaysiakini.com/news/783373" rel="noopener noreferrer">Sumber: Malaysiakini / prosiding reman →</a></div></article>''', '''<article id="news-2026-09-06-jamil-reman-checkpoint" class="timeline-item" data-topic="enforcement"><time datetime="2026-09-06">06 SEP 2026</time><div><div class="meta-row"><span class="status process">Reman disambung · hingga 8 Sep</span><span class="source-grade">Gred B</span></div><h3>Mahkamah sambung reman bekas menteri dua hari lagi</h3><p>Mahkamah Majistret Putrajaya membenarkan permohonan SPRM menyambung reman dari 7 hingga 8 September bagi siasatan isu pajakan hotel TH di Arab Saudi. SPRM menyatakan siasatan dibuat di bawah Seksyen 16(a)(A) Akta SPRM 2009. Reman tidak membuktikan kesalahan dan belum ada pertuduhan disahkan terhadap beliau.</p><a href="/raventrace-my/news/2026/09/06/jamil-khir-reman-checkpoint/">Baca artikel →</a><br><a href="https://web26.bernama.com/bm/jenayah_mahkamah/news.php?id=2603643" rel="noopener noreferrer">Sumber: Bernama →</a></div></article>''', 'news Jamil current'),
    ('''<article id="news-2026-09-03-thp-bina-rm72000" class="timeline-item" data-topic="court">''', '''<article id="news-2026-09-03-ujsb-sukuk-refinancing" class="timeline-item" data-topic="governance"><time datetime="2026-09-03">03 SEP 2026</time><div><div class="meta-row"><span class="status context">Kewangan · pembiayaan semula</span><span class="source-grade">Gred B</span></div><h3>RM11.5 bilion sukuk UJSB bukan bailout baharu</h3><p>Penjelasan yang dilaporkan Bernama menyatakan sukuk baharu menggantikan sukuk terdahulu UJSB dan memberi aliran tunai tahunan kepada TH. Ia ialah pembiayaan semula dan tidak patut ditambah sekali lagi sebagai kerugian baharu.</p><a href="/raventrace-my/investigations/rci-tabung-haji/#money">Semak konteks kewangan →</a><br><a href="https://bernama.com/radio/news.php?id=2602611" rel="noopener noreferrer">Sumber: Bernama →</a></div></article>\n      <article id="news-2026-09-03-thp-bina-rm72000" class="timeline-item" data-topic="court">''', 'news sukuk insert'),
    ('<a href="/raventrace-my/investigations/rci-tabung-haji/">Siasatan</a>', '<a href="/raventrace-my/investigations/">Siasatan</a>', 'news investigation nav first'),
    ('/assets/js/raven.js?v=3.2.0', '/assets/js/raven.js?v=3.4.0', 'news JS cache bust'),
])

# CASEFILE v17: static evidence layer updated so page is current even before JS enhancement.
patch_all('investigations/rci-tabung-haji/index.html', [
    ('CASEFILE RCI Tabung Haji v16:', 'CASEFILE RCI Tabung Haji v17:', 'case meta version'),
    ('hingga 5 September 2026.', 'hingga 7 September 2026.', 'case meta cutoff'),
    ('CASEFILE · RCI-TH-2026 · v16', 'CASEFILE · RCI-TH-2026 · v17', 'case utility version'),
    ('Data cut-off · 5 Sep 2026 MYT', 'Data cut-off · 7 Sep 2026 · awal pagi MYT', 'case hero cutoff'),
    ('Revisi laman · 6 Sep 2026', 'Revisi laman · 7 Sep 2026', 'case revision date'),
    ('''<article class="person-card"><div><span>03</span><span class="status process">Direman · hingga 6 Sep</span></div><h3>Datuk Seri Jamil Khir Baharom</h3><p class="role">Menteri di JPM (Hal Ehwal Agama) · 2009–2018</p><p>Direman lima hari bagi membantu siasatan isu pajakan hotel TH di Arab Saudi. Tiada pertuduhan disahkan terhadap beliau setakat 5 September; reman bukan dapatan kesalahan.</p><a href="#s22">S22</a></article>''', '''<article class="person-card"><div><span>03</span><span class="status process">Reman disambung · hingga 8 Sep</span></div><h3>Datuk Seri Jamil Khir Baharom</h3><p class="role">Menteri di JPM (Hal Ehwal Agama) · 2009–2018</p><p>Selepas reman lima hari bermula 2 September, Mahkamah Majistret Putrajaya membenarkan sambungan dua hari dari 7 hingga 8 September. SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009. Reman bukan pertuduhan atau dapatan kesalahan.</p><a href="#s22">S22</a> <a href="#s49">S49</a></article>''', 'case Jamil ledger'),
    ('<h2>Empat perkembangan yang mengubah kedudukan kes.</h2>\n          <div class="trace-stack">', '<h2>Lima perkembangan yang mengubah kedudukan kes.</h2>\n          <div class="trace-stack">\n            <article class="trace-card" data-sep6-update="true"><div class="trace-head"><span>JEJAK / 00</span><time datetime="2026-09-06">6 Sep 2026 · Mahkamah Majistret Putrajaya</time></div><div class="meta-row"><span class="status process">Reman disambung · hingga 8 Sep</span><span class="source-grade">Gred B</span></div><h3>Mahkamah membenarkan sambungan reman bekas menteri dua hari lagi.</h3><dl><div><dt>Apa diketahui?</dt><dd>Reman disambung untuk 7–8 September selepas permohonan SPRM.</dd></div><div><dt>Asas siasatan?</dt><dd>Ketua Pesuruhjaya SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009 berkaitan isu pajakan hotel TH di Arab Saudi.</dd></div><div><dt>Had</dt><dd>Tiada pertuduhan atau sabitan boleh disimpulkan daripada sambungan reman.</dd></div></dl><p class="inline-sources"><a href="#s49">S49</a> <a href="#s22">S22</a></p></article>', 'case latest remand card'),
    ('''<article><time>3–4 Sep</time><h3>Pertikaian Madinah–Rashid</h3><p>Dua versi awam bercanggah mengenai apa yang berlaku ketika Madinah hadir untuk prosiding RCI pada 2022.</p></article>''', '''<article><time>3–4 Sep</time><h3>Pertikaian Madinah–Rashid</h3><p>Dua versi awam bercanggah mengenai apa yang berlaku ketika Madinah hadir untuk prosiding RCI pada 2022.</p></article>\n            <article><time>6 Sep</time><h3>Reman bekas menteri disambung</h3><p>Mahkamah Majistret Putrajaya membenarkan sambungan reman dua hari bagi 7–8 September. SPRM menyatakan siasatan di bawah Seksyen 16(a)(A).</p></article>''', 'case timeline extension'),
    ('''</div>\n          <div class="metric-glossary"><h3>Bagaimana mekanisme UJSB bekerja</h3>''', '''</div>\n          <div class="case-warning light"><strong>Follow-up kewangan · RM11.5b sukuk</strong><span>Terbitan sukuk RM11.5 bilion yang dilaporkan pada September diterangkan sebagai pembiayaan semula/rollover sukuk UJSB terdahulu, bukan bailout baharu atau kerugian baharu. Struktur baharu dilaporkan memberi aliran tunai tahunan kepada TH.</span><p class="inline-sources"><a href="#s50">S50</a></p></div>\n          <div class="metric-glossary"><h3>Bagaimana mekanisme UJSB bekerja</h3>''', 'case sukuk note'),
    ('<li>Apakah hasil reman Jamil Khir selepas 6 September dan keputusan AGC bagi Al-Rawda?</li>', '<li>Apakah tindakan selepas sambungan reman Jamil Khir berakhir 8 September, dan apakah keputusan AGC bagi kertas Al-Rawda?</li>', 'case unknown Jamil'),
    ('Dapatkan nombor kes, helaian pertuduhan, status Al-Rawda selepas reman 6 September, empat fail NFA, transkrip RCI, audit forensik dan status lengkap 25 syor.', 'Dapatkan nombor kes, helaian pertuduhan, tindakan selepas reman 8 September, keputusan AGC bagi Al-Rawda, empat fail NFA, transkrip RCI, audit forensik dan status lengkap enam syor RCI yang masih berjalan.', 'case verify next'),
    ('''<li id="s43"><span>B</span><a href="https://www.utusan.com.my/nasional/2026/09/rci-th-beberapa-individu-akan-didakwa/" rel="noopener noreferrer">Pengumuman 4 + 10 pertuduhan dirancang</a><small>Utusan · 2 Sep</small></li>''', '''<li id="s43"><span>B</span><a href="https://www.utusan.com.my/nasional/2026/09/rci-th-beberapa-individu-akan-didakwa/" rel="noopener noreferrer">Pengumuman 4 + 10 pertuduhan dirancang</a><small>Utusan · 2 Sep</small></li>\n            <li id="s44"><span>B</span><a href="https://www.malaymail.com/news/malaysia/2026/09/03/tabung-haji-act-amendments-in-final-stages-before-parliamentary-tabling-says-th-ceo/233776" rel="noopener noreferrer">19/25 syor selesai + pindaan Akta >90%</a><small>Malay Mail / Bernama · 3 Sep</small></li>\n            <li id="s45"><span>B</span><a href="https://berita.rtm.gov.my/nasional/senarai-berita-nasional/senarai-artikel/pengurusan-tabung-haji-wajar-dikawal-selia-lebih-ketat-pm/" rel="noopener noreferrer">PM sokong kawal selia TH lebih ketat</a><small>RTM / Bernama · 4 Sep</small></li>\n            <li id="s46"><span>B</span><a href="https://berita.rtm.gov.my/nasional/senarai-berita-nasional/senarai-artikel/isu-th-rakyat-mahu-siasatan-sprm-dilaksana-secara-telus/" rel="noopener noreferrer">Beberapa responden mahu siasatan lebih telus</a><small>RTM · 5 Sep</small></li>\n            <li id="s47"><span>E</span><a href="https://www.malaymail.com/news/what-you-think/2026/09/05/what-happens-when-too-few-people-say-no-noor-adwa-sulaiman/233962" rel="noopener noreferrer">Analisis tadbir urus: semak dan imbang</a><small>Malay Mail · komentar · 5 Sep</small></li>\n            <li id="s48"><span>B</span><a href="https://www.malaysiakini.com/news/783373" rel="noopener noreferrer">Reman awal Jamil Khir lima hari</a><small>Malaysiakini · 2 Sep</small></li>\n            <li id="s49"><span>B</span><a href="https://web26.bernama.com/bm/jenayah_mahkamah/news.php?id=2603643" rel="noopener noreferrer">Reman bekas menteri disambung dua hari</a><small>Bernama · 6 Sep · Mahkamah Majistret Putrajaya</small></li>\n            <li id="s50"><span>B</span><a href="https://bernama.com/radio/news.php?id=2602611" rel="noopener noreferrer">RM11.5b sukuk UJSB ialah pembiayaan semula</a><small>Bernama · 3 Sep</small></li>''', 'case sources 44-50'),
    ('<strong>Data cut-off:</strong> 5 September 2026 MYT. <strong>Semakan laman:</strong> 6 September 2026.', '<strong>Data cut-off:</strong> 7 September 2026 · awal pagi MYT. <strong>Semakan laman:</strong> 7 September 2026.', 'case source note cutoff'),
    ('<a aria-current="page" href="/raventrace-my/investigations/rci-tabung-haji/">Siasatan</a>', '<a aria-current="page" href="/raventrace-my/investigations/">Siasatan</a>', 'case investigation nav'),
    ('<script src="/raventrace-my/assets/js/raven.js?v=3.0.0" defer></script>', '<script src="/raventrace-my/assets/js/raven.js?v=3.4.0" defer></script>', 'case JS cache bust'),
])

# Jamil story body and static article-level copy. OG image metadata is refreshed separately by Phase 2B pipeline.
patch_all('news/2026/09/06/jamil-khir-reman-checkpoint/index.html', [
    ('Semakan RAVEN-Trace mengenai tamat tempoh reman Jamil Khir Baharom pada 6 September 2026 dalam siasatan susulan RCI Tabung Haji.', 'Semakan RAVEN-Trace mengenai sambungan reman Jamil Khir Baharom hingga 8 September 2026 dalam siasatan susulan RCI Tabung Haji.', 'story meta description'),
    ('<title>Reman Jamil Khir tamat 6 Sep — status seterusnya belum disahkan | RAVEN-Trace</title>', '<title>Reman Jamil Khir disambung dua hari hingga 8 Sep | RAVEN-Trace</title>', 'story title'),
    ('<meta property="og:title" content="Reman Jamil Khir tamat 6 Sep — status seterusnya belum disahkan">', '<meta property="og:title" content="Reman Jamil Khir disambung dua hari hingga 8 Sep">', 'story og title'),
    ('<meta property="og:description" content="Reman lima hari dijadual berakhir 6 September. Setakat semakan RAVEN-Trace, belum ada rekod awam yang mengesahkan pembebasan, lanjutan reman atau pertuduhan.">', '<meta property="og:description" content="Mahkamah Majistret Putrajaya membenarkan permohonan SPRM menyambung reman dua hari lagi, dari 7 hingga 8 September. Reman bukan pertuduhan atau sabitan.">', 'story og description'),
    ('<meta property="article:modified_time" content="2026-09-06T14:20:00+08:00">', '<meta property="article:modified_time" content="2026-09-07T01:55:00+08:00">', 'story modified time'),
    ('<div class="meta-row"><span class="status unknown">UNKNOWN · outcome belum disahkan</span><span class="source-grade">Gred B</span></div><h1>Reman Jamil Khir tamat 6 Sep. Status seterusnya belum disahkan.</h1><p class="story-dek">Reman lima hari bermula 2 September bagi membantu siasatan berkaitan pajakan hotel Tabung Haji di Arab Saudi. Tamat reman tidak dengan sendirinya bermaksud bebas daripada siasatan atau bakal didakwa.</p><div class="story-meta"><span>Diterbitkan 6 Sep 2026</span><span>Semakan terakhir · 2:20 petang MYT</span></div>', '<div class="meta-row"><span class="status process">REMAN DISAMBUNG · BELUM DIDAKWA</span><span class="source-grade">Gred B</span></div><h1>Reman Jamil Khir disambung dua hari hingga 8 September.</h1><p class="story-dek">Mahkamah Majistret Putrajaya membenarkan permohonan SPRM menyambung reman bagi 7–8 September dalam siasatan berkaitan pajakan hotel TH di Arab Saudi. Sambungan reman bukan pertuduhan dan bukan sabitan.</p><div class="story-meta"><span>Diterbitkan 6 Sep 2026</span><span>Dikemas kini · 7 Sep 2026 · awal pagi MYT</span></div>', 'story hero'),
    ('data-share-title="RAVEN-Trace: Reman Jamil Khir tamat 6 Sep" data-share-text="Reman lima hari dijadual berakhir 6 September. Setakat semakan RAVEN-Trace, status seterusnya belum disahkan melalui rekod awam."', 'data-share-title="RAVEN-Trace: Reman Jamil Khir disambung hingga 8 Sep" data-share-text="Mahkamah membenarkan sambungan reman dua hari bagi 7–8 September. SPRM menyatakan siasatan di bawah Seksyen 16(a)(A). Reman bukan pertuduhan atau sabitan."', 'story share copy'),
    ('<article><b>FACT</b><p>Jamil Khir direman lima hari bermula 2 September hingga Ahad, 6 September.</p></article><article><b>UNKNOWN</b><p>Belum ada rekod awam yang kami temui mengesahkan pembebasan, lanjutan reman atau pertuduhan selepas tempoh itu.</p></article><article><b>HAD BUKTI</b><p>Reman ialah alat siasatan. Ia bukan sabitan dan tidak menentukan keputusan akhir sesuatu kertas siasatan.</p></article>', '<article><b>FACT</b><p>Selepas reman lima hari bermula 2 September, mahkamah membenarkan sambungan dua hari bagi 7–8 September.</p></article><article><b>FACT</b><p>SPRM menyatakan siasatan dibuat di bawah Seksyen 16(a)(A) Akta SPRM 2009 berkaitan isu pajakan hotel TH di Arab Saudi.</p></article><article><b>HAD BUKTI</b><p>Tiada pertuduhan atau sabitan boleh disimpulkan daripada reman. Status selepas 8 September masih belum diketahui.</p></article>', 'story fact grid'),
    ('<h2>Apa yang diketahui?</h2><p>Bekas Menteri di Jabatan Perdana Menteri (Hal Ehwal Agama) itu direman bagi membantu siasatan SPRM berkaitan pajakan hotel Tabung Haji di Arab Saudi. Laporan prosiding reman menyatakan perintah lima hari itu berjalan hingga 6 September.</p><h2>Apa yang belum diketahui?</h2><p>Setakat semakan RAVEN-Trace pada 6 September, belum ada sumber awam yang kami semak yang mengesahkan tindakan seterusnya terhadap beliau selepas tamat tempoh reman. Oleh itu status kekal <strong>UNKNOWN</strong>.</p>', '<h2>Apa yang diketahui?</h2><p>Bekas Menteri di Jabatan Perdana Menteri (Hal Ehwal Agama) itu pada awalnya direman lima hari hingga 6 September. Pada 6 September, Mahkamah Majistret Putrajaya membenarkan permohonan SPRM menyambung reman dua hari lagi bagi 7–8 September. Ketua Pesuruhjaya SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009.</p><h2>Apa yang belum diketahui?</h2><p>Setakat awal 7 September, belum ada pertuduhan disahkan terhadap beliau. Tindakan selepas tamat sambungan reman pada 8 September — sama ada dibebaskan, dipohon reman lanjut jika dibenarkan undang-undang, atau perkembangan pendakwaan — kekal <strong>UNKNOWN</strong> sehingga ada rekod baharu.</p>', 'story known unknown'),
    ('“Reman tamat” tidak boleh ditukar secara automatik menjadi “dibebaskan daripada kes”, dan ia juga tidak boleh ditukar menjadi “akan didakwa”. Kedua-dua kesimpulan memerlukan rekod baharu.', '“Reman disambung” tidak boleh ditukar menjadi “akan didakwa” atau “bersalah”. Ia hanya menunjukkan mahkamah membenarkan tempoh siasatan lanjut atas permohonan SPRM.', 'story wording callout'),
    ('<li><a href="https://theedgemalaysia.com/node/816532" rel="noopener noreferrer">The Edge — former minister remanded over Saudi hotel lease issue</a><small>Laporan beratribusi kepada SPRM dan prosiding mahkamah.</small></li>', '<li><a href="https://theedgemalaysia.com/node/816532" rel="noopener noreferrer">The Edge — former minister remanded over Saudi hotel lease issue</a><small>Laporan beratribusi kepada SPRM dan prosiding mahkamah.</small></li><li><a href="https://web26.bernama.com/bm/jenayah_mahkamah/news.php?id=2603643" rel="noopener noreferrer">Bernama — reman bekas menteri disambung dua hari</a><small>6 Sep 2026 · Mahkamah Majistret Putrajaya; Seksyen 16(a)(A) Akta SPRM 2009.</small></li>', 'story new source'),
    ('<p><strong>UNKNOWN</strong></p><p>Tamat tempoh reman diketahui; outcome selepasnya belum disahkan.</p>', '<p><strong>REMAN HINGGA 8 SEP</strong></p><p>Sambungan reman disahkan. Pertuduhan belum disahkan; tindakan selepas 8 September masih belum diketahui.</p>', 'story side status'),
    ('/assets/js/raven.js?v=3.3.0', '/assets/js/raven.js?v=3.4.0', 'story JS cache bust'),
])

# Narrative enhancer must not overwrite v17 with the old early-morning 6 Sep state.
patch_all('assets/js/raven-narrative.js', [
    ("addSourceRow('s48','B','https://www.malaysiakini.com/news/783373','Reman Jamil Khir hingga 6 Sep','Malaysiakini · prosiding reman');", "addSourceRow('s48','B','https://www.malaysiakini.com/news/783373','Reman awal Jamil Khir lima hari','Malaysiakini · 2 Sep');\n  addSourceRow('s49','B','https://web26.bernama.com/bm/jenayah_mahkamah/news.php?id=2603643','Reman bekas menteri disambung dua hari','Bernama · 6 Sep · Mahkamah Majistret Putrajaya');\n  addSourceRow('s50','B','https://bernama.com/radio/news.php?id=2602611','RM11.5b sukuk UJSB ialah pembiayaan semula','Bernama · 3 Sep');", 'narrative sources'),
    ("heroDate.textContent = 'Data cut-off · 6 Sep 2026 · awal pagi MYT'", "heroDate.textContent = 'Data cut-off · 7 Sep 2026 · awal pagi MYT'", 'narrative cutoff'),
    ("hingga 6 September 2026.'", "hingga 7 September 2026.'", 'narrative description cutoff'),
    ("<strong>Data cut-off:</strong> 6 September 2026 · awal pagi MYT. <strong>Semakan laman:</strong> 6 September 2026.", "<strong>Data cut-off:</strong> 7 September 2026 · awal pagi MYT. <strong>Semakan laman:</strong> 7 September 2026.", 'narrative source note'),
    ("status.className = 'status unknown'; status.textContent = 'Reman tamat · 6 Sep · outcome belum diumumkan';", "status.className = 'status process'; status.textContent = 'Reman disambung · hingga 8 Sep';", 'narrative Jamil status'),
    ("body.textContent = 'Direman lima hari bagi membantu siasatan isu pajakan hotel TH di Arab Saudi. Tempoh reman dijadual berakhir 6 September. Setakat semakan awal pagi, belum ada rekod awam yang mengesahkan sama ada beliau dibebaskan, reman dilanjutkan atau akan didakwa.';", "body.textContent = 'Selepas reman lima hari bermula 2 September, Mahkamah Majistret Putrajaya membenarkan sambungan dua hari bagi 7–8 September. SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009. Reman bukan pertuduhan atau dapatan kesalahan.';", 'narrative Jamil body'),
    ("if (!refs.some((a) => a.getAttribute('href') === '#s48')) {\n      const a = document.createElement('a'); a.href = '#s48'; a.textContent = 'S48'; jamil.append(' ', a);\n    }", "if (!refs.some((a) => a.getAttribute('href') === '#s49')) {\n      const a = document.createElement('a'); a.href = '#s49'; a.textContent = 'S49'; jamil.append(' ', a);\n    }", 'narrative Jamil source'),
    ("<h3>Tempoh reman Jamil Khir berakhir hari ini; status seterusnya belum diumumkan.</h3><dl><div><dt>Apa diketahui?</dt><dd>Reman lima hari bermula 2 September dan dijadual berakhir 6 September.</dd></div><div><dt>Apa belum diketahui?</dt><dd>Belum ada rekod awam yang mengesahkan pembebasan, lanjutan reman atau pertuduhan.</dd></div><div><dt>Kenapa penting?</dt><dd>Tamat tempoh reman tidak boleh diterjemah secara automatik sebagai bebas daripada siasatan atau sebagai bakal didakwa.</dd></div></dl><p class=\"inline-sources\"><a href=\"#s48\">S48</a> <a href=\"#s22\">S22</a></p>", "<h3>Mahkamah membenarkan sambungan reman bekas menteri dua hari hingga 8 September.</h3><dl><div><dt>Apa diketahui?</dt><dd>Reman disambung bagi 7–8 September selepas permohonan SPRM.</dd></div><div><dt>Asas siasatan?</dt><dd>SPRM menyatakan kes disiasat di bawah Seksyen 16(a)(A) Akta SPRM 2009.</dd></div><div><dt>Had</dt><dd>Reman bukan pertuduhan atau sabitan; tindakan selepas 8 September masih belum diketahui.</dd></div></dl><p class=\"inline-sources\"><a href=\"#s49\">S49</a> <a href=\"#s22\">S22</a></p>", 'narrative latest card copy'),
])

# README status only; no claim beyond what is now in the publication.
patch_all('README.md', [
    ('The RCI Tabung Haji investigation remains at **CASEFILE v16**, reconciled through **6 September 2026 MYT**.', 'The RCI Tabung Haji investigation is now at **CASEFILE v17**, reconciled through **7 September 2026 · early morning MYT**.' , 'README v17 status'),
    ('Current work includes the Jamil Khir remand checkpoint, transparency reporting, governance reform progress, disputed Al-Rawda metrics, the public correction ledger, Share System v2.1, and the Source Room Navigator.', 'Current work includes the Jamil Khir remand extension through 8 September, transparency reporting, governance reform progress, UJSB refinancing context, disputed Al-Rawda metrics, the public correction ledger, Share System v2.1, and the Source Room Navigator.', 'README current work'),
])
