from pathlib import Path

p = Path('investigations/rci-tabung-haji/narratives/index.html')
s = p.read_text()

repls = {
'''<article><h3>“Sakau duit umat Islam”</h3><p><span class="status claim">DAKWAAN / SLOGAN POLITIK</span></p><p>Bahasa “sakau” digunakan dalam perdebatan politik untuk menggambarkan dakwaan penyelewengan atau kehilangan dana.</p><p><b>Apa rekod tunjuk?</b> RCI dan kerajaan merekodkan kerugian, susut nilai, masalah tadbir urus dan transaksi yang memerlukan pemeriksaan lanjut. Itu tidak bermaksud setiap ringgit kerugian ialah wang yang dicuri.</p><p><b>Had:</b> Bekas Ketua Audit Negara Madinah Mohamad berkata audit semasa tempohnya tidak menemui bukti kecurian atau penyelewengan. Kenyataan itu terhad kepada skop audit dan tidak menutup kemungkinan isu tadbir urus atau siasatan jenayah lain.</p></article>''':
'''<article><h3>“Sakau duit umat Islam”</h3><p><span class="status claim">DAKWAAN / SLOGAN POLITIK</span></p><p><b>Siapa menggunakan naratif ini?</b> Frasa “sakau” muncul dalam perdebatan politik dan media sosial sebagai bahasa untuk menggambarkan dakwaan penyelewengan atau kehilangan dana.</p><p><b>Apa rekod tunjuk?</b> RCI dan kenyataan kerajaan merekodkan kerugian, susut nilai, masalah tadbir urus dan transaksi yang memerlukan pemeriksaan lanjut.</p><p><b>Konteks yang sering tertinggal:</b> Kerugian, impairment atau transaksi bermasalah tidak dengan sendirinya membuktikan wang dicuri. Bekas Ketua Audit Negara Madinah Mohamad pula berkata audit dalam tempohnya tidak menemui bukti kecurian atau penyelewengan; kenyataan itu terhad kepada skop audit tersebut.</p><p><b>Verdict Raven:</b> Slogan politik yang merumuskan isu kompleks secara agresif. Rekod menyokong kewujudan masalah serius, tetapi tidak menyokong kesimpulan bahawa setiap kerugian ialah kecurian.</p></article>''',

'''<article><h3>“Aset TH dijual kepada bukan Islam / China”</h3><p><span class="status disputed">TIDAK DISOKONG REKOD YANG DISEMAK</span></p><p>Menteri Agama Zulkifli Hasan menafikan dakwaan itu di Dewan Rakyat dan menyatakan aset dipindahkan kepada Urusharta Jamaah Sdn Bhd (UJSB), sebuah syarikat tujuan khas milik kerajaan.</p><p><b>Kesimpulan:</b> Berdasarkan struktur transaksi yang diterangkan secara rasmi, dakwaan bahawa aset itu dijual kepada “China” atau bukan Islam tidak disokong oleh rekod yang kami semak.</p></article>''':
'''<article><h3>“Aset TH dijual kepada bukan Islam / China”</h3><p><span class="status disputed">TIDAK DISOKONG REKOD YANG DISEMAK</span></p><p><b>Siapa menggunakan naratif ini?</b> Dakwaan ini beredar dalam wacana politik dan media sosial apabila pemindahan aset TH kepada UJSB dipersoalkan.</p><p><b>Apa rekod tunjuk?</b> Menteri Agama Zulkifli Hasan menafikan dakwaan itu di Dewan Rakyat dan menyatakan aset dipindahkan kepada Urusharta Jamaah Sdn Bhd (UJSB), sebuah syarikat tujuan khas milik kerajaan.</p><p><b>Konteks yang sering tertinggal:</b> Pemindahan aset dalam pelan penstrukturan semula bukan perkara yang sama dengan jualan kepada pihak asing atau bukan Islam. Namun, pemilikan benefisial dan rantaian transaksi paling kukuh jika disokong terus oleh dokumen korporat serta transaksi primer.</p><p><b>Verdict Raven:</b> Berdasarkan rekod yang telah disemak, dakwaan bahawa aset TH “dijual kepada China” atau bukan Islam tidak disokong. Status ini tidak dinaikkan kepada “palsu mutlak” tanpa audit dokumen primer penuh.</p></article>''',

'''<article><h3>“Dedah penuh, bukan separuh-separuh”</h3><p><span class="status fact">FAKTA · POSISI POLITIK</span></p><p>Beberapa pemimpin UMNO dan PN/PAS mahukan tempoh selepas 2017/2018 turut diperiksa. Dr Akmal Saleh membangkitkan UJSB; PAS melalui Takiyuddin Hassan menggesa RCI baharu bagi tempoh 2018 hingga kini.</p><p><b>Apa penting?</b> Permintaan untuk siasatan lebih luas ialah posisi politik yang boleh disahkan. Sama ada ia perlu dibuat melalui RCI baharu, PAC atau siasatan agensi ialah persoalan dasar yang berasingan.</p></article>''':
'''<article><h3>“Dedah penuh, bukan separuh-separuh”</h3><p><span class="status fact">FAKTA · POSISI POLITIK</span></p><p><b>Siapa menggunakan naratif ini?</b> Beberapa pemimpin UMNO dan PN/PAS mahukan tempoh selepas 2017/2018 turut diperiksa. Dr Akmal Saleh membangkitkan UJSB; PAS melalui Takiyuddin Hassan menggesa RCI baharu bagi tempoh 2018 hingga kini.</p><p><b>Apa rekod tunjuk?</b> Permintaan untuk pemeriksaan lebih luas memang wujud dalam rekod awam dan boleh disahkan sebagai posisi politik.</p><p><b>Konteks yang sering tertinggal:</b> Keperluan meneliti tempoh selepas 2017/2018 tidak membatalkan dapatan RCI bagi 2014–2020. Dua persoalan itu boleh dinilai serentak.</p><p><b>Verdict Raven:</b> Soalan dasar yang sah. Perbahasan sebenar ialah mekanisme paling sesuai — RCI baharu, PAC, audit forensik atau siasatan agensi — dan bukannya sama ada tempoh selepas itu langsung tidak patut diperiksa.</p></article>''',

'''<article><h3>“RCI baharu ialah cubaan alih fokus”</h3><p><span class="status context">KESIMPULAN SEMENTARA</span></p><p>Analisis media tertentu melihat desakan RCI baharu sebagai usaha mengalihkan perhatian daripada dapatan tempoh 2014–2020 kepada tindakan pemulihan era selepas 2018.</p><p><b>Had:</b> Ini tafsiran terhadap kesan politik desakan tersebut. Ia bukan bukti tentang niat sebenar UMNO, PAS atau mana-mana individu.</p></article>''':
'''<article><h3>“RCI baharu ialah cubaan alih fokus”</h3><p><span class="status context">ANALISIS / INFERENCE · MOTIF TIDAK DIBUKTIKAN</span></p><p><b>Siapa menggunakan naratif ini?</b> Analisis media dan pengkritik tertentu melihat desakan RCI baharu sebagai usaha mengalihkan perhatian daripada dapatan 2014–2020 kepada tindakan dan pemulihan selepas 2018.</p><p><b>Apa rekod tunjuk?</b> Perubahan fokus politik memang boleh diperhatikan: daripada dapatan RCI pertama kepada UJSB dan tempoh selepas 2018.</p><p><b>Konteks yang sering tertinggal:</b> Perubahan fokus atau kesan politik tidak membuktikan motif orang yang meminta RCI baharu.</p><p><b>Verdict Raven:</b> Munasabah sebagai analisis terhadap kesan naratif, tetapi tidak boleh dipersembahkan sebagai fakta tentang niat UMNO, PAS atau mana-mana individu.</p></article>''',

'''<article><h3>“RCI sekarang sudah cukup; tak perlu RCI kedua”</h3><p><span class="status claim">POSISI / HUJAH</span></p><p>AMK mempersoalkan keperluan menubuhkan RCI baharu dan menegaskan RCI bukan alat mencari keputusan yang memihak kepada parti. IKRAM pula berpendapat siasatan agensi sedia ada memadai.</p><p><b>Had:</b> Ini pandangan politik dan masyarakat sivil, bukan dapatan undang-undang bahawa RCI kedua mustahil atau tidak sah.</p></article>''':
'''<article><h3>“RCI sekarang sudah cukup; tak perlu RCI kedua”</h3><p><span class="status claim">POSISI / HUJAH DASAR</span></p><p><b>Siapa menggunakan naratif ini?</b> AMK mempersoalkan keperluan menubuhkan RCI baharu, manakala IKRAM berpendapat siasatan agensi sedia ada memadai.</p><p><b>Apa rekod tunjuk?</b> RCI sedia ada mempunyai skop tertentu dan telah menghasilkan dapatan serta cadangan. Dalam masa sama, PAC, SPRM, PDRM dan audit forensik mempunyai fungsi berbeza.</p><p><b>Konteks yang sering tertinggal:</b> Kewujudan RCI pertama tidak dengan sendirinya membuktikan RCI kedua tidak diperlukan; begitu juga permintaan RCI kedua tidak membuktikan agensi sedia ada gagal.</p><p><b>Verdict Raven:</b> Ini pilihan dasar, bukan fakta. Soalan utama ialah jurang bukti atau kuasa apa yang benar-benar memerlukan RCI baharu berbanding mekanisme sedia ada.</p></article>''',

'''<article><h3>“UMNO satu suara tentang RCI kedua”</h3><p><span class="status disputed">GAMBARAN TERLALU MUDAH</span></p><p>Rekod awam menunjukkan posisi yang tidak seragam. Ada pemimpin UMNO yang mahu tempoh lebih luas disiasat, tetapi Ahmad Zahid Hamidi menyokong cadangan badan khas di bawah PAC untuk meneliti pengurusan selepas 2017.</p><p><b>Kesimpulan:</b> Lebih tepat menyebut terdapat beberapa pendekatan dalam UMNO, bukan satu posisi tunggal.</p></article>''':
'''<article><h3>“UMNO satu suara tentang RCI kedua”</h3><p><span class="status disputed">GAMBARAN TERLALU MUDAH</span></p><p><b>Siapa menggunakan naratif ini?</b> Wacana awam kadang-kadang merumuskan semua kenyataan pemimpin UMNO sebagai satu pendirian tunggal mengenai RCI kedua.</p><p><b>Apa rekod tunjuk?</b> Posisi awam tidak seragam. Ada pemimpin UMNO yang mahu tempoh lebih luas disiasat, manakala Ahmad Zahid Hamidi menyokong cadangan badan khas di bawah PAC untuk meneliti pengurusan selepas 2017.</p><p><b>Konteks yang sering tertinggal:</b> Kenyataan seorang atau beberapa pemimpin tidak semestinya sama dengan pendirian rasmi parti.</p><p><b>Verdict Raven:</b> Lebih tepat menyebut terdapat beberapa pendekatan dalam UMNO, bukan satu posisi tunggal yang seragam.</p></article>'''
}

for old, new in repls.items():
    if old not in s:
        raise SystemExit(f'Missing expected block: {old[:80]}')
    s = s.replace(old, new)

s = s.replace('<h2>Enam naratif yang paling kerap muncul.</h2>', '<h2>Enam naratif paling kerap muncul — dibedah sebagai claim, rekod, konteks yang tertinggal dan verdict.</h2>')
s = s.replace('Halaman ini tidak menentukan siapa “menang” naratif. Ia memisahkan kenyataan politik, rekod yang boleh disemak, tafsiran dan perkara yang masih belum diketahui.', 'Halaman ini tidak menentukan siapa “menang” naratif. Ia menguji setiap frame melalui empat lapisan: siapa menggunakannya, apa rekod tunjuk, konteks yang sering tertinggal, dan verdict RAVEN-Trace.')

p.write_text(s)

# QA
out = p.read_text()
for marker in ['Siapa menggunakan naratif ini?', 'Konteks yang sering tertinggal:', 'Verdict Raven:']:
    assert out.count(marker) >= 6, (marker, out.count(marker))
assert 'ANALISIS / INFERENCE · MOTIF TIDAK DIBUKTIKAN' in out
assert 'Soalan dasar yang sah.' in out
assert 'tidak menyokong kesimpulan bahawa setiap kerugian ialah kecurian' in out
print('Narrative forensic upgrade V2 PASS')
